//para compilar e gerar um arquivo JS usa-se o comando TSC mais o caminho e nome do arquivo...
//para rodar o arquivo javascript gerado pelo type script usa-se o comando NODE mais o nome do arquivo...
//para rodar um arquivo typescript usa-se o comando NODE mais o nome do arquivo...